// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UnitDataGeneratorStart(arg1) {
  return window['go']['main']['App']['UnitDataGeneratorStart'](arg1);
}

export function UnitDataGeneratorStatus() {
  return window['go']['main']['App']['UnitDataGeneratorStatus']();
}

export function UnitDataGeneratorStop() {
  return window['go']['main']['App']['UnitDataGeneratorStop']();
}
